config/routes.rb
Rails.application.routes.draw do
  get 'items/create'

  devise_for :users

  get  'welcome/index'

  get  'welcome/about'

  root 'users#show'

  resources :users do
    resources :items
  end

#  resources :items

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user

  def from_time
	  created_at
	end

	def to_time
	  7-(from_time)
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user

    if @item.save
      flash[:notice] = "Item was saved."
      redirect_to current_user
    else
      flash[:error] = "There was an error saving the item. Please try again."
      render :new
    end
  end

  def destroy
      @item = current_user.items.find(params[:id])

      if @item.destroy
        flash[:notice] = "Item completed!"
      else
        flash[:alert] = "There was an error deleting the item, please try again."
      end

      respond_to do |format|
        format.html
        format.js
      end

    end

  private

  def item_params
    params.require(:item).permit(:name, :user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def index
  end

  def edit
  end

  def show
    if !current_user.nil?
      @user = current_user
      @item = Item.new
      @items = @user.items
    else
      redirect_to new_user_registration_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to users_show_path(current_user)
    end
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<h3> Add New Item </h3>

<%= form_for [@user, @item] do |f| %>
<form class="form-inline">
  <div class="form-group">
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter a new task" %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit Task", class: 'btn btn-default pull-right' %>
  </div>
</form>
<% end %>

app/views/items/_item.html.erb
<% @items.each do |item| %>
  <div class="media" id="item-<%= item.id %>">
    <div class="media-body">
      <h4 class="media-heading">
        <%= item.name %>
        <% if current_user == @user %>
          : <%= link_to '', [item.user, item], method: :delete, remote: true, class: 'glyphicon glyphicon-ok' %>
        <% end %>
      </h4>
      <small>
        <%= distance_of_time_in_words(Time.now, item.created_at.to_date + 7 ) %> left <br>
      </small>
    </div>
  </div>
<% end %>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
  $("#item-<%= @item.id %>").fadeOut(1300);
<% else %>
  $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:alert] %></div>");
<% end %>

app/views/items/new.html.erb
<h1> New Item </h1>

  <div class="col-md-8">
    <%= render partial: 'items/form', locals: { item: @item } %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Knock Out</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="pull-right login">
         <% if user_signed_in? %>
               Signed in as: <strong><%= current_user.email %></strong>
               <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
               <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
         <% else %>
               <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %>
               <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
          <% end %>
      </div>
      <ul class="nav nav-tabs">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", welcome_about_path %></li>
      </ul>

      <%= yield %>
    </div>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/sedit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class="container">
  <h1><%= @user.email %></h1>

  <% if current_user == @user %>
    <div class="col-md-8">
      <%= render partial: 'items/form', locals: { user: @user, item: @item } %>
    </div>
    <% end %>

    <div class="col-md-8">
      <%= render partial: 'items/item', locals: { user: @user, items: @items } %>
    </div>

app/views/welcome/about.html.erb
<h1> About Knock Out</h1>

<p> A self-destructing to-do list to make your life more productive.</p>

app/views/welcome/index.html.erb
<div class="welcome_box">
    <h3 class='welcome_elements'> Knock Out </h3>

    <p> A self-destructing to-do list to keep you focused on the things that really matter </p>

  </div>

</div>